# Generated by Django 4.2.3 on 2023-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Soft", "Soft")], max_length=10
            ),
        ),
    ]
